# Generated by Django 5.0 on 2026-09-16 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('certification', models.BooleanField()),
                ('eco_rating', models.IntegerField()),
                ('expire_at', models.DateTimeField()),
            ],
        ),
    ]
