# Generated by Django 6.1.1 on 2026-09-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='eco_rating',
            field=models.FloatField(),
        ),
    ]
